### **Registratered Email : sadmanwahid307@gmail.com**

# **Name : Sadman Wahid**

### **Q(0)**

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

In [ ]:
df = pd.read_csv('staff_data.csv')
df.head(2)

   emp_id  emp_age  emp_salary        role
0     101       54       51725  HR Manager
1     102       23       38495  Accountant

# **Question 1: Numpy**

### **Q(1)**

In [ ]:
emp_age = np.array(df['emp_age'])

emp_salary =np.array(df['emp_salary'])

print(emp_age)
print(emp_salary)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]
[51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]

In [ ]:
#data type
print(emp_age.dtype)

print(emp_salary.dtype)

int64
int64

In [ ]:
#dimensions
print(emp_age.ndim)

print(emp_salary.ndim)

1
1

In [ ]:
#shape
print(emp_age.shape)

print(emp_salary.shape)

(50,)
(50,)

In [ ]:
#number of elements
print(emp_age.size)

print(emp_salary.size)

50
50

### **Q(2)**

In [ ]:
#max and min salary
print(emp_salary.max())

print(emp_salary.min())

94722
35452

In [ ]:
#average salary
print(emp_salary.mean())

68409.48

In [ ]:
#average age
print(emp_age.mean())

35.44

### **Q(3)**

In [ ]:
#Extract employees who are aged between 25 and 40,AND Emp_salary : have salary greater than 50,000
condition= (emp_age >= 25) & (emp_age <= 40) & (emp_salary>50000)
print(condition.dtype)

bool

In [ ]:
manip_age =emp_age[condition] #condition following emp_age
manip_salary = emp_salary[condition] #condition following emp_salary

print()
print(manip_age)
print()
print(manip_salary)

[37 37 35 38 31 29 38 27 32 26 37 26 30 30 27 25 31]

[72187 58915 92864 90494 68641 56879 83682 94722 74146 78354 79898 59682
 73700 84188 52013 63326 59727]

In [ ]:
print(condition.sum()) #how many elements are following the condition

17

### **Q(4)**

In [ ]:
updated_age = np.where(emp_age < emp_age.mean(), emp_age + 4, emp_age + 2) #Add 4 years if age is less than the average age Add 2 years if age is greater than or equal to the average age

In [ ]:
print(emp_age) #printing both array og and updated
print()
print(updated_age)

[54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

[56 27 24 45 39 39 25 39 28 40 35 39 33 40 31 47 53 50 24 36 53 55 25 30
 55 39 30 25 47 34 24 49 55 55 27 28 25 34 31 29 41 24 49 43 26 54 44 56
 35 52]

In [ ]:
print(emp_age.mean()) #avg of og age

35.44

In [ ]:
print(updated_age.mean()) #avg of updated_age

38.48

### **Q(5)**

In [ ]:
total_og_salary = emp_salary.sum()

new_salary = emp_salary* 1.8  #incresing salary by 8%

In [ ]:
print(new_salary)

[ 93105.   69291.   63813.6 148131.  129936.6 106047.  137086.2 167155.2
 137079.  162889.2 123553.8  86542.2 102382.2 150627.6 170499.6 163873.8
  88018.2 123739.2 113736.6 133462.8 136153.8  85820.4 138168.  141037.2
 109051.2 143816.4 107427.6 129398.4  91954.8 132660.  148590.  128604.6
 136980.  130084.2 131965.2 157370.4 169968.6 151538.4  93623.4 113986.8
  79912.8 107100.   99941.4 105483.6 163429.2  73909.8 148195.8 131486.4
 107508.6  90716.4]

In [ ]:
total_new_salary = new_salary.sum()

In [ ]:
print(total_og_salary)
print(total_new_salary)

3420474
6156853.200000001

In [ ]:
print((total_new_salary - total_og_salary).round(3))

2736379.2

**Question 2: Pandas**

### **Q6**

In [ ]:
df= pd.read_csv("staff_data.csv")
df.head(3) #showing first 3 row

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

In [ ]:
df.describe()

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

### **Q7**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

In [ ]:
df2=df.drop(columns=['emp_salary']) #to making dataset with only emp_id,emp_age,role only
df2

    emp_id  emp_age                 role
0      101       54           HR Manager
1      102       23           Accountant
2      103       20   Operations Manager
3      104       43     Digital Marketer
4      105       37    Backend Developer
5      106       37           HR Manager
6      107       21    Backend Developer
7      108       35      Sales Executive
8      109       24      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
15     116       45    Financial Analyst
16     117       51      Sales Executive
17     118       48   Operations Manager
18     119       20   Software Developer
19     120       32    Backend Developer
20     121       51      Sales Executive
21     122       53      Sales Executive
22     123       21           Accountant
23     124       26   Software Developer
24     125       53         HR Executive
25     126       37   Operations Manager
26     127       26     Digital Marketer
27     128       21         HR Executive
28     129       45   Software Developer
29     130       30           Accountant
30     131       20      Sales Executive
31     132       47  Marketing Executive
32     133       53     Digital Marketer
33     134       53    Backend Developer
34     135       23   Software Developer
35     136       24   Software Developer
36     137       21      Sales Executive
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
41     142       20     Digital Marketer
42     143       47         HR Executive
43     144       41           Accountant
44     145       22         HR Executive
45     146       52           HR Manager
46     147       42   Software Developer
47     148       54   Software Developer
48     149       31     Digital Marketer
49     150       50  Marketing Executive

In [ ]:
df2[(df2['emp_age'] >= 25) & (df2['emp_age'] <= 45)] #filtering with age condition

    emp_id  emp_age                 role
3      104       43     Digital Marketer
4      105       37    Backend Developer
5      106       37           HR Manager
7      108       35      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
15     116       45    Financial Analyst
19     120       32    Backend Developer
23     124       26   Software Developer
25     126       37   Operations Manager
26     127       26     Digital Marketer
28     129       45   Software Developer
29     130       30           Accountant
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
43     144       41           Accountant
46     147       42   Software Developer
48     149       31     Digital Marketer

In [ ]:
df2 = df2.sort_values(by='emp_id') #sorting by emp_id ascending
df2

    emp_id  emp_age                 role
0      101       54           HR Manager
1      102       23           Accountant
2      103       20   Operations Manager
3      104       43     Digital Marketer
4      105       37    Backend Developer
5      106       37           HR Manager
6      107       21    Backend Developer
7      108       35      Sales Executive
8      109       24      Sales Executive
9      110       38         HR Executive
10     111       31    Backend Developer
11     112       35  Marketing Executive
12     113       29      Sales Executive
13     114       38   Operations Manager
14     115       27     Digital Marketer
15     116       45    Financial Analyst
16     117       51      Sales Executive
17     118       48   Operations Manager
18     119       20   Software Developer
19     120       32    Backend Developer
20     121       51      Sales Executive
21     122       53      Sales Executive
22     123       21           Accountant
23     124       26   Software Developer
24     125       53         HR Executive
25     126       37   Operations Manager
26     127       26     Digital Marketer
27     128       21         HR Executive
28     129       45   Software Developer
29     130       30           Accountant
30     131       20      Sales Executive
31     132       47  Marketing Executive
32     133       53     Digital Marketer
33     134       53    Backend Developer
34     135       23   Software Developer
35     136       24   Software Developer
36     137       21      Sales Executive
37     138       30           Accountant
38     139       27           HR Manager
39     140       25      Sales Executive
40     141       39  Marketing Executive
41     142       20     Digital Marketer
42     143       47         HR Executive
43     144       41           Accountant
44     145       22         HR Executive
45     146       52           HR Manager
46     147       42   Software Developer
47     148       54   Software Developer
48     149       31     Digital Marketer
49     150       50  Marketing Executive

In [ ]:
df2.tail(3) #showing last 3 row

    emp_id  emp_age                 role
47     148       54   Software Developer
48     149       31     Digital Marketer
49     150       50  Marketing Executive

### **Q8**

In [ ]:
print(df[df['role'].isin(['HR Manager', 'HR Executive'])]) # filter by Hr role

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager

In [ ]:
print(df['role'].isin(['HR Manager', 'HR Executive']).sum()) #counting emp number whose role is HR

9

### **Q9**

In [ ]:
df = df.sort_values(by='emp_age') #ascending sorting by emp_age
df

    emp_id  emp_age  emp_salary                 role
2      103       20       35452   Operations Manager
18     119       20       63187   Software Developer
30     131       20       82550      Sales Executive
41     142       20       59500     Digital Marketer
22     123       21       76760           Accountant
27     128       21       71888         HR Executive
36     137       21       94427      Sales Executive
6      107       21       76159    Backend Developer
44     145       22       90794         HR Executive
34     135       23       73314   Software Developer
1      102       23       38495           Accountant
35     136       24       87428   Software Developer
8      109       24       76155      Sales Executive
39     140       25       63326      Sales Executive
26     127       26       59682     Digital Marketer
23     124       26       78354   Software Developer
14     115       27       94722     Digital Marketer
38     139       27       52013           HR Manager
12     113       29       56879      Sales Executive
37     138       30       84188           Accountant
29     130       30       73700           Accountant
10     111       31       68641    Backend Developer
48     149       31       59727     Digital Marketer
19     120       32       74146    Backend Developer
11     112       35       48079  Marketing Executive
7      108       35       92864      Sales Executive
5      106       37       58915           HR Manager
25     126       37       79898   Operations Manager
4      105       37       72187    Backend Developer
9      110       38       90494         HR Executive
13     114       38       83682   Operations Manager
40     141       39       44396  Marketing Executive
43     144       41       58602           Accountant
46     147       42       82331   Software Developer
3      104       43       82295     Digital Marketer
15     116       45       91041    Financial Analyst
28     129       45       51086   Software Developer
42     143       47       55523         HR Executive
31     132       47       71447  Marketing Executive
17     118       48       68744   Operations Manager
49     150       50       50398  Marketing Executive
16     117       51       48899      Sales Executive
20     121       51       75641      Sales Executive
45     146       52       41061           HR Manager
33     134       53       72269    Backend Developer
24     125       53       60584         HR Executive
21     122       53       47678      Sales Executive
32     133       53       76100     Digital Marketer
0      101       54       51725           HR Manager
47     148       54       73048   Software Developer

In [ ]:
df = df.sort_values(by='emp_salary', ascending=False) #descending sort by emp_salary
print(df)

    emp_id  emp_age  emp_salary                 role
14     115       27       94722     Digital Marketer
36     137       21       94427      Sales Executive
7      108       35       92864      Sales Executive
15     116       45       91041    Financial Analyst
44     145       22       90794         HR Executive
9      110       38       90494         HR Executive
35     136       24       87428   Software Developer
37     138       30       84188           Accountant
13     114       38       83682   Operations Manager
30     131       20       82550      Sales Executive
46     147       42       82331   Software Developer
3      104       43       82295     Digital Marketer
25     126       37       79898   Operations Manager
23     124       26       78354   Software Developer
22     123       21       76760           Accountant
6      107       21       76159    Backend Developer
8      109       24       76155      Sales Executive
32     133       53       76100     Digital Marketer
20     121       51       75641      Sales Executive
19     120       32       74146    Backend Developer
29     130       30       73700           Accountant
34     135       23       73314   Software Developer
47     148       54       73048   Software Developer
33     134       53       72269    Backend Developer
4      105       37       72187    Backend Developer
27     128       21       71888         HR Executive
31     132       47       71447  Marketing Executive
17     118       48       68744   Operations Manager
10     111       31       68641    Backend Developer
39     140       25       63326      Sales Executive
18     119       20       63187   Software Developer
24     125       53       60584         HR Executive
48     149       31       59727     Digital Marketer
26     127       26       59682     Digital Marketer
41     142       20       59500     Digital Marketer
5      106       37       58915           HR Manager
43     144       41       58602           Accountant
12     113       29       56879      Sales Executive
42     143       47       55523         HR Executive
38     139       27       52013           HR Manager
0      101       54       51725           HR Manager
28     129       45       51086   Software Developer
49     150       50       50398  Marketing Executive
16     117       51       48899      Sales Executive
11     112       35       48079  Marketing Executive
21     122       53       47678      Sales Executive
40     141       39       44396  Marketing Executive
45     146       52       41061           HR Manager
1      102       23       38495           Accountant
2      103       20       35452   Operations Manager

In [ ]:
print(df[['emp_id', 'role', 'emp_salary']].head(5)) #show top 5 employees for emp_id,role,emp_salary

    emp_id               role  emp_salary
14     115   Digital Marketer       94722
36     137    Sales Executive       94427
7      108    Sales Executive       92864
15     116  Financial Analyst       91041
44     145       HR Executive       90794

### **Q10**

In [ ]:
df

    emp_id  emp_age  emp_salary                 role
14     115       27       94722     Digital Marketer
36     137       21       94427      Sales Executive
7      108       35       92864      Sales Executive
15     116       45       91041    Financial Analyst
44     145       22       90794         HR Executive
9      110       38       90494         HR Executive
35     136       24       87428   Software Developer
37     138       30       84188           Accountant
13     114       38       83682   Operations Manager
30     131       20       82550      Sales Executive
46     147       42       82331   Software Developer
3      104       43       82295     Digital Marketer
25     126       37       79898   Operations Manager
23     124       26       78354   Software Developer
22     123       21       76760           Accountant
6      107       21       76159    Backend Developer
8      109       24       76155      Sales Executive
32     133       53       76100     Digital Marketer
20     121       51       75641      Sales Executive
19     120       32       74146    Backend Developer
29     130       30       73700           Accountant
34     135       23       73314   Software Developer
47     148       54       73048   Software Developer
33     134       53       72269    Backend Developer
4      105       37       72187    Backend Developer
27     128       21       71888         HR Executive
31     132       47       71447  Marketing Executive
17     118       48       68744   Operations Manager
10     111       31       68641    Backend Developer
39     140       25       63326      Sales Executive
18     119       20       63187   Software Developer
24     125       53       60584         HR Executive
48     149       31       59727     Digital Marketer
26     127       26       59682     Digital Marketer
41     142       20       59500     Digital Marketer
5      106       37       58915           HR Manager
43     144       41       58602           Accountant
12     113       29       56879      Sales Executive
42     143       47       55523         HR Executive
38     139       27       52013           HR Manager
0      101       54       51725           HR Manager
28     129       45       51086   Software Developer
49     150       50       50398  Marketing Executive
16     117       51       48899      Sales Executive
11     112       35       48079  Marketing Executive
21     122       53       47678      Sales Executive
40     141       39       44396  Marketing Executive
45     146       52       41061           HR Manager
1      102       23       38495           Accountant
2      103       20       35452   Operations Manager

In [ ]:
df.loc[df['role'].isin(['Software Developer', 'Backend Developer']), 'new_salary'] = df['emp_salary'] * 1.12 #increasing salary with conditions
df

    emp_id  emp_age  emp_salary                 role  new_salary
14     115       27       94722     Digital Marketer         NaN
36     137       21       94427      Sales Executive         NaN
7      108       35       92864      Sales Executive         NaN
15     116       45       91041    Financial Analyst         NaN
44     145       22       90794         HR Executive         NaN
9      110       38       90494         HR Executive         NaN
35     136       24       87428   Software Developer    97919.36
37     138       30       84188           Accountant         NaN
13     114       38       83682   Operations Manager         NaN
30     131       20       82550      Sales Executive         NaN
46     147       42       82331   Software Developer    92210.72
3      104       43       82295     Digital Marketer         NaN
25     126       37       79898   Operations Manager         NaN
23     124       26       78354   Software Developer    87756.48
22     123       21       76760           Accountant         NaN
6      107       21       76159    Backend Developer    85298.08
8      109       24       76155      Sales Executive         NaN
32     133       53       76100     Digital Marketer         NaN
20     121       51       75641      Sales Executive         NaN
19     120       32       74146    Backend Developer    83043.52
29     130       30       73700           Accountant         NaN
34     135       23       73314   Software Developer    82111.68
47     148       54       73048   Software Developer    81813.76
33     134       53       72269    Backend Developer    80941.28
4      105       37       72187    Backend Developer    80849.44
27     128       21       71888         HR Executive         NaN
31     132       47       71447  Marketing Executive         NaN
17     118       48       68744   Operations Manager         NaN
10     111       31       68641    Backend Developer    76877.92
39     140       25       63326      Sales Executive         NaN
18     119       20       63187   Software Developer    70769.44
24     125       53       60584         HR Executive         NaN
48     149       31       59727     Digital Marketer         NaN
26     127       26       59682     Digital Marketer         NaN
41     142       20       59500     Digital Marketer         NaN
5      106       37       58915           HR Manager         NaN
43     144       41       58602           Accountant         NaN
12     113       29       56879      Sales Executive         NaN
42     143       47       55523         HR Executive         NaN
38     139       27       52013           HR Manager         NaN
0      101       54       51725           HR Manager         NaN
28     129       45       51086   Software Developer    57216.32
49     150       50       50398  Marketing Executive         NaN
16     117       51       48899      Sales Executive         NaN
11     112       35       48079  Marketing Executive         NaN
21     122       53       47678      Sales Executive         NaN
40     141       39       44396  Marketing Executive         NaN
45     146       52       41061           HR Manager         NaN
1      102       23       38495           Accountant         NaN
2      103       20       35452   Operations Manager         NaN

In [ ]:
df['new_salary'].value_counts()

new_salary
97919.36    1
92210.72    1
87756.48    1
85298.08    1
83043.52    1
82111.68    1
81813.76    1
80941.28    1
80849.44    1
76877.92    1
70769.44    1
57216.32    1
Name: count, dtype: int64

In [ ]:
df.loc[df['new_salary'].isna(), 'new_salary'] = df['emp_salary'] * 1.05 #after filling value for software and backend developer filling nan value with 5% increasing salary

In [ ]:
df

    emp_id  emp_age  emp_salary                 role  new_salary
14     115       27       94722     Digital Marketer    99458.10
36     137       21       94427      Sales Executive    99148.35
7      108       35       92864      Sales Executive    97507.20
15     116       45       91041    Financial Analyst    95593.05
44     145       22       90794         HR Executive    95333.70
9      110       38       90494         HR Executive    95018.70
35     136       24       87428   Software Developer    97919.36
37     138       30       84188           Accountant    88397.40
13     114       38       83682   Operations Manager    87866.10
30     131       20       82550      Sales Executive    86677.50
46     147       42       82331   Software Developer    92210.72
3      104       43       82295     Digital Marketer    86409.75
25     126       37       79898   Operations Manager    83892.90
23     124       26       78354   Software Developer    87756.48
22     123       21       76760           Accountant    80598.00
6      107       21       76159    Backend Developer    85298.08
8      109       24       76155      Sales Executive    79962.75
32     133       53       76100     Digital Marketer    79905.00
20     121       51       75641      Sales Executive    79423.05
19     120       32       74146    Backend Developer    83043.52
29     130       30       73700           Accountant    77385.00
34     135       23       73314   Software Developer    82111.68
47     148       54       73048   Software Developer    81813.76
33     134       53       72269    Backend Developer    80941.28
4      105       37       72187    Backend Developer    80849.44
27     128       21       71888         HR Executive    75482.40
31     132       47       71447  Marketing Executive    75019.35
17     118       48       68744   Operations Manager    72181.20
10     111       31       68641    Backend Developer    76877.92
39     140       25       63326      Sales Executive    66492.30
18     119       20       63187   Software Developer    70769.44
24     125       53       60584         HR Executive    63613.20
48     149       31       59727     Digital Marketer    62713.35
26     127       26       59682     Digital Marketer    62666.10
41     142       20       59500     Digital Marketer    62475.00
5      106       37       58915           HR Manager    61860.75
43     144       41       58602           Accountant    61532.10
12     113       29       56879      Sales Executive    59722.95
42     143       47       55523         HR Executive    58299.15
38     139       27       52013           HR Manager    54613.65
0      101       54       51725           HR Manager    54311.25
28     129       45       51086   Software Developer    57216.32
49     150       50       50398  Marketing Executive    52917.90
16     117       51       48899      Sales Executive    51343.95
11     112       35       48079  Marketing Executive    50482.95
21     122       53       47678      Sales Executive    50061.90
40     141       39       44396  Marketing Executive    46615.80
45     146       52       41061           HR Manager    43114.05
1      102       23       38495           Accountant    40419.75
2      103       20       35452   Operations Manager    37224.60

In [ ]:
df['increase_of_salary'] = df['new_salary'] - df['emp_salary']

In [ ]:
df[['role','emp_salary','new_salary','increase_of_salary']] #showing dataset according the given condition

                   role  emp_salary  new_salary  increase_of_salary
14     Digital Marketer       94722    99458.10             4736.10
36      Sales Executive       94427    99148.35             4721.35
7       Sales Executive       92864    97507.20             4643.20
15    Financial Analyst       91041    95593.05             4552.05
44         HR Executive       90794    95333.70             4539.70
9          HR Executive       90494    95018.70             4524.70
35   Software Developer       87428    97919.36            10491.36
37           Accountant       84188    88397.40             4209.40
13   Operations Manager       83682    87866.10             4184.10
30      Sales Executive       82550    86677.50             4127.50
46   Software Developer       82331    92210.72             9879.72
3      Digital Marketer       82295    86409.75             4114.75
25   Operations Manager       79898    83892.90             3994.90
23   Software Developer       78354    87756.48             9402.48
22           Accountant       76760    80598.00             3838.00
6     Backend Developer       76159    85298.08             9139.08
8       Sales Executive       76155    79962.75             3807.75
32     Digital Marketer       76100    79905.00             3805.00
20      Sales Executive       75641    79423.05             3782.05
19    Backend Developer       74146    83043.52             8897.52
29           Accountant       73700    77385.00             3685.00
34   Software Developer       73314    82111.68             8797.68
47   Software Developer       73048    81813.76             8765.76
33    Backend Developer       72269    80941.28             8672.28
4     Backend Developer       72187    80849.44             8662.44
27         HR Executive       71888    75482.40             3594.40
31  Marketing Executive       71447    75019.35             3572.35
17   Operations Manager       68744    72181.20             3437.20
10    Backend Developer       68641    76877.92             8236.92
39      Sales Executive       63326    66492.30             3166.30
18   Software Developer       63187    70769.44             7582.44
24         HR Executive       60584    63613.20             3029.20
48     Digital Marketer       59727    62713.35             2986.35
26     Digital Marketer       59682    62666.10             2984.10
41     Digital Marketer       59500    62475.00             2975.00
5            HR Manager       58915    61860.75             2945.75
43           Accountant       58602    61532.10             2930.10
12      Sales Executive       56879    59722.95             2843.95
42         HR Executive       55523    58299.15             2776.15
38           HR Manager       52013    54613.65             2600.65
0            HR Manager       51725    54311.25             2586.25
28   Software Developer       51086    57216.32             6130.32
49  Marketing Executive       50398    52917.90             2519.90
16      Sales Executive       48899    51343.95             2444.95
11  Marketing Executive       48079    50482.95             2403.95
21      Sales Executive       47678    50061.90             2383.90
40  Marketing Executive       44396    46615.80             2219.80
45           HR Manager       41061    43114.05             2053.05
1            Accountant       38495    40419.75             1924.75
2    Operations Manager       35452    37224.60             1772.60